//FILE: js/elements/foot/foot_plain.js
/*******************************************************************************
*                                                                              *
*  This file has been generated by bmc.                                        *
*  Customizations should be done in bmc/elem/elements/<element_name>/elem.def. *
*                                                                              *
*******************************************************************************/



//class:
function foot_plain(pdiv,wrap)
{
//constructor:
    this.wrap=wrap;
    this.box=document.createElement("div");
    pdiv.appendChild(this.box);

    
//public:
    this.destroy=function()
    {
        pdiv.removeChild(this.box);
    }
    this.preset=function()
    {
        var o="\
                <div align='center'>\
                    loading...\
                </div>";
        this.box.innerHTML=o;

    }
    
//private:
    this.setup=function(s)
    {
        elements_setup(s,this.wrap,"plain");
    }
}

main_loader.ready();

