//FILE: js/elements/foot/foot_wrapper.js
/*******************************************************************************
*                                                                              *
*  This file has been generated by bmc.                                        *
*  Customizations should be done in bmc/elem/elements/<element_name>/elem.def. *
*                                                                              *
*******************************************************************************/

main_loader.load("js/elements/foot/foot_simple.js");
main_loader.load("js/elements/foot/foot_plain.js");

main_loader.load("js/http/common.js");


//class:
function foot_wrapper(pdiv,style)
{
//constructor:
    this.object;
    this.name="foot";
    
    
    switch(style)
    {
        case "simple":
            this.object=new foot_simple(pdiv,this);
            break;
        case "plain":
            this.object=new foot_plain(pdiv,this);
            break;
        case "inv":
            this.object=new foot_plain(pdiv,this);
            break;
        default:
            this.object=new foot_plain(pdiv,this);
    }
    
//public:
    this.destroy=function()
    {
        this.object.destroy();
    }
    
    this.load=function(url)
    {
        httpGetAsync(url,receive_text,this);
    }
    
    
    
    
    this.setup=function(s)
    {
        elements_setup(s,this,style);

    }
    
    
    
    this.scroll=function(x,y)
    {
        window.scrollTo(x,y);
    }
    
    
//private:
    
    
}

main_loader.ready();

