/*******************************************************************************
*                                                                              *
*  This is the main site setup                                                 *
*                                                                              *
*  This file is generated by bmc.                                              *
*  Customizations should be done in bmc/sites/<module_name>/main/main_js.def.  *
*                                                                              *
*******************************************************************************/
//(0)--------------------
//   breaking frames
//-----------------------
if(self.parent.frames.length!=0){self.parent.location='index.php';}
//(1)--------------------
//   The site
//-----------------------
var site=123;
//settings
var css_substyle="4";
var copyright_info="Copyright © 2017-2019<br>by Andreas Pollhammer";
//(2)--------------------
//   base-url
//-----------------------
var baseurl=this.location.protocol+"//"+this.location.host
if(this.location.host.substr(0,4)=="www.")baseurl=baseurl+"/";
else baseurl=baseurl+"/";
if(this.location.host=="localhost")baseurl=this.location.protocol+"//"+this.location.host+"/sites/demo/";
//(3)--------------------
//   Global elements
//-----------------------
var domel={};
var e_mbox=null;
//(4)--------------------
//   Other global vars
//-----------------------
var main_handler;
//(5)--------------------
//   Status-bar
//-----------------------
var global_loadstat=new loadstat(document.getElementById("MAIN"));
//(6)--------------------
//   Loader
//-----------------------
var main_loader=new script_loader(loader_start,loader_anim,29);
//(7)--------------------
//   Base-System
//-----------------------
main_loader.load("page.js");
main_loader.load("js/mods/main.js");
//MODULES_MINIMUM
//(9)--------------------
//   Elements
//-----------------------
main_loader.load("layouts/elem/setup.js");
main_loader.load("js/elements/sysmod_box/sysmod_box.js");
main_loader.load("js/elements/sysmod_box/sysmod_box.css");
//the page layout
main_loader.load("layouts/page/minisite.js");
//custom element layouts
main_loader.load("layouts/elem/main/compact/setup.js");
main_loader.load("layouts/elem/foot/setup.js");
//(10)--------------------
//   MAIN
//-----------------------
function loader_start()
{
    if(typeof loader_start_extra == 'function')loader_start_extra();
    main_handler=new Handler("main");
    console.log("start()");
    global_loadstat.destroy();
    //load_page(currentpage);
    setgstyle(gstyle);
    startup=false;
    setTimeout(startup_check,10000);
}
//(11)--------------------
//   anim. while loading
//-----------------------
function loader_anim(p)
{
    global_loadstat.onEvent("update",p);
}
//(12)--------------------
//    extra files
//------------------------