/*******************************************************************************
*                                                                              *
*  Basic user defined page layouts                                             *
*                                                                              *
*  This file has been generated by bmc.                                        *
*  Customizations should be done in bmc/sites/<module_name>/main/page_js.def.  *
*                                                                              *
*******************************************************************************/
function update()
{
    __update();
}
function u_load_page(page)
{
    __u_load_page(page);
}
function u_chstyle(old_style,new_style)
{
    __u_chstyle(old_style,new_style);
}
function u_setlang(newLang)
{
    __u_setlang(newLang);
}

main_loader.ready();