//FILE: js/elements/main/main_wrapper.js
/*******************************************************************************
*                                                                              *
*  This file has been generated by bmc.                                        *
*  Customizations should be done in bmc/elem/elements/<element_name>/elem.def. *
*                                                                              *
*******************************************************************************/

main_loader.load("js/elements/main/main_simple.js");
main_loader.load("js/elements/main/main_plain.js");

main_loader.load("js/http/common.js");


//class:
function main_wrapper(pdiv,style)
{
//constructor:
    this.object;
    this.name="main";
    this.layout="left";
    this.vars_context=new file_storage();
    this.content_token="";

    
    switch(style)
    {
        case "simple":
            this.object=new main_simple(pdiv,this);
            break;
        case "plain":
            this.object=new main_plain(pdiv,this);
            break;
        case "inv":
            this.object=new main_plain(pdiv,this);
            break;
        default:
            this.object=new main_plain(pdiv,this);
    }
    
//public:
    this.destroy=function()
    {
        this.object.destroy();
    }
    
    this.load=function(url)
    {
        httpGetAsync(url,receive_text,this);
    }
    
    
    this.load2=function(content,layout)
    {
        this.object.layout=layout;
        this.content_token=content;
        
        this.object.preset();
        
        this.reset();
        
        if(content.charAt(0)=='_')
        {
            httpGetAsync(baseurl+"php/"+content.substr(1)+".php",receive_text,this);
        }
        else
        {
            httpGetAsync(baseurl+"content/"+lang+"/"+content+".txt",receive_text,this);
        }
    }
    
    
    this.reset=function()
    {
        //this.postloadfunction=null;
        pdiv.scrollTop=0;

    }
    
    
    this.setup=function(s)
    {
        this.object.setup(s);
        window.scrollTo(0,0);

    }
    
    
    
    this.scroll=function(x,y)
    {
        window.scrollTo(x,y);
    }
    
    
//private:
    
    
}

main_loader.ready();

