//FILE: js/elements/fmain/fmain_plain.js
//TIME: Fri Oct  4 18:40:45 2019
/*******************************************************************************
*                                                                              *
*  This file has been generated by bmc!                                        *
*  Copyright 2019 by Andreas Pollhammer.                                       *
*  web:   http://www.andreaspollhammer.com                                     *
*  email: apoll500@gmail.com                                                   *
*                                                                              *
*******************************************************************************/
/*******************************************************************************
*                                                                              *
*  Customizations should be done in bmc/elem/elements/<element_name>/elem.def. *
*                                                                              *
*******************************************************************************/



//class:
function fmain_plain(pdiv,wrap)
{
//constructor:
    this.adiv=adiv;
    
    this.pdiv=pdiv;
    this.wrap=wrap;
    
    this.box=document.createElement("div");
    pdiv.appendChild(this.box);

    
//public:
    this.set_adiv=function(adiv)
    {
    }
    this.destroy=function()
    {
        pdiv.removeChild(this.box);
    }
    this.preset=function()
    {
        var o="\
                <div align='center'>\
                    loading...\
                </div>";
        this.box.innerHTML=o;

    }
    this.onResize=function()
    {
        
    }
    
//private:
    this.setup=function(s)
    {
        elements_setup(s,this.wrap,"plain");
    }
}

main_loader.ready();

