//FILE: js/elements/fmain/fmain_simple.js
//TIME: Fri Oct  4 18:40:45 2019
/*******************************************************************************
*                                                                              *
*  This file has been generated by bmc!                                        *
*  Copyright 2019 by Andreas Pollhammer.                                       *
*  web:   http://www.andreaspollhammer.com                                     *
*  email: apoll500@gmail.com                                                   *
*                                                                              *
*******************************************************************************/
/*******************************************************************************
*                                                                              *
*  Customizations should be done in bmc/elem/elements/<element_name>/elem.def. *
*                                                                              *
*******************************************************************************/

main_loader.load("js/animate/animate.js");
function close_local_info_banner()
{
    var e=document.getElementById("local_info_banner");
    e.innerHTML="";
}
//class:
function fmain_simple(adiv,pdiv,wrap)
{
//constructor:
    this.adiv=adiv;
    
    this.pdiv=pdiv;
    this.wrap=wrap;
    
    this.formatter=null;
    this.box=document.createElement("div");
    this.d1=document.createElement("div");
    this.d2=document.createElement("div");
    this.d3=document.createElement("div");
    this.d4=document.createElement("div");
    this.d5=document.createElement("div");
    this.title=document.createElement("div");
    this.content=document.createElement("div");
    this.box.className="simple_box_d0";
    //this.d1.className="simple_box_d1_maxi";
    //this.d2.className="simple_box_d2_maxi";
    //this.d3.className="simple_box_d3_maxi";
    this.d4.align="left";
    this.title.className="simple_box_title";
    this.box.appendChild(this.d1);
    this.d1.appendChild(this.d2);
    this.d2.appendChild(this.d3);
    this.d3.appendChild(this.d4);
    this.d4.appendChild(this.title);
    this.d4.appendChild(this.content);
    this.d2.appendChild(this.d5);
    this.d5.innerHTML="<br><br><br><div id='local_info_banner' style='font-size:11pt;position:absolute;bottom:20px;right:20px;padding:2px;border:solid 1px #CCCCCC;border-radius:10px;background-color:#FFFFFF;'><span style='color:#AAAAAA;'><a href='JavaScript:load_page(\"contact\")' style='color:#AAAAAA;'><i>Kontakt</i></a> | <a href='JavaScript:load_page(\"impre\")' style='color:#AAAAAA;'><i>Impressum</i></a> | <a href='JavaScript:load_page(\"datainfo\")' style='color:#AAAAAA;'><i>Datenschutz</i></a> | <a href='JavaScript:close_local_info_banner()'>X</a></span></div>";
    
    pdiv.appendChild(this.box);

    main_elements_add(this);
    this.layout="left";
    this.rstyle="null";
    this.flapminh=40;

//public:
    this.set_adiv=function(adiv)
    {
        this.adiv=adiv;//menu
    }
    this.destroy=function()
    {
        main_elements_remove(this);
        pdiv.removeChild(this.box);
    }
    
    this.onEvent=function(type,evt)
    {
        switch(type)
        {
            case "resize":
                this.onResize();
                break;
        }
    }
    
    this.preset=function()
    {
        var o="\
                <div align='center'>\
                    loading...\
                </div>";
        this.title.innerHTML=o;
        this.content.innerHTML="";
        this.onResize();

    }
    /*
    this.mbox=function()
    {
        return this.d4;
    }
    */
    
//private:
    
    this.check_inputs=function()
    {
        this.check_inputs2("");
    }
    this.check_inputs2=function(module)
    {
        if(this.formatter!=null)
        {
            var w=0;
            if(this.adiv)w=parseInt(this.adiv.left_admin_box.anim_width);
            this.formatter.update3(Math.min(600,screenx-w),"check_input",module);
        }
        this.onResize();
    }
    
    this.onResize=function()
    {
        var w=0;
        if(this.adiv)w=parseInt(this.adiv.left_admin_box.anim_width);
        if(screenx<680+w)
        {
            this.rstyle="mini";
            this.d1.className="simple_box_d1_mini";
            this.d2.className="simple_box_d2_mini";
            this.d3.className="simple_box_d3_mini";
        }
        else
        {
            this.rstyle="maxi";
            this.d1.className="simple_box_d1_maxi";
            this.d2.className="simple_box_d2_maxi";
            this.d3.className="simple_box_d3_maxi";
        }
        if(this.adiv)
        {
            this.box.style.marginLeft=w+"px";
            this.box.style.width=(screenx-w)+"px";
            this.box.style.height=(screeny-32)+"px";
        }
        if(this.formatter!=null)
        {
            this.formatter.update(Math.min(600,screenx-w));
        }

    }
    
    this.animate=function(p)
    {
    }
    this.end_anim=function()
    {
        this.onResize();
    }
    this.update=function()
    {
    }
    
    this.setup=function(s)
    {
        elements_setup(s,this.wrap,"simple");
    }
}

main_loader.ready();

