//FILE: js/elements/fmain/fmain_wrapper.js
//TIME: Fri Oct  4 18:40:45 2019
/*******************************************************************************
*                                                                              *
*  This file has been generated by bmc!                                        *
*  Copyright 2019 by Andreas Pollhammer.                                       *
*  web:   http://www.andreaspollhammer.com                                     *
*  email: apoll500@gmail.com                                                   *
*                                                                              *
*******************************************************************************/
/*******************************************************************************
*                                                                              *
*  Customizations should be done in bmc/elem/elements/<element_name>/elem.def. *
*                                                                              *
*******************************************************************************/

main_loader.load("js/elements/fmain/fmain_simple.js");
main_loader.load("js/elements/fmain/fmain_plain.js");

main_loader.load("js/http/common.js");


//class:
function fmain_wrapper(adiv,pdiv,style)
{
//constructor:
    this.object;
    this.name="main";
    this.layout="left";
    this.vars_context=new file_storage();
    this.content_token="";

    
    switch(style)
    {
        case "simple":
            this.object=new fmain_simple(adiv,pdiv,this);
            break;
        case "plain":
            this.object=new fmain_plain(pdiv,this);
            break;
        case "inv":
            this.object=new fmain_plain(pdiv,this);
            break;
        default:
            this.object=new fmain_plain(pdiv,this);
    }
    
//public:
    this.destroy=function()
    {
        this.object.destroy();
    }
    
    this.load=function(url)
    {
        httpGetAsync(url,receive_text,this);
    }
    
    
    this.load2=function(content,layout)
    {
        this.object.layout=layout;
        this.content_token=content;
        
        this.object.preset();
        
        this.reset();
        
        if(content.charAt(0)=='_')
        {
            httpGetAsync(baseurl+"php/"+content.substr(1)+".php",receive_text,this);
        }
        else
        {
            httpGetAsync(baseurl+"content/"+lang+"/"+content+".txt",receive_text,this);
        }
    }
    
    
    this.reset=function()
    {
        //this.postloadfunction=null;
        pdiv.scrollTop=0;

    }
    
    
    this.setup=function(s)
    {
        this.object.formatter=null;
        elements_setup(s,this,style);
        if(this.postloadfunction)this.postloadfunction(this.postloadfunction_elem,this.postloadfunction_data);

    }
    
    
    this.scroll=function(x,y)
    {
        this.object.box.scrollTop=y;
        this.object.box.scrollLeft=x;
    }
    
    
    
//private:
    
    this.check_inputs=function()
    {
        this.object.check_inputs();
    }
    this.check_inputs2=function(module)
    {
        this.object.check_inputs2(module);
    }
    
    
    this.postloadfunction=null;
    this.postloadfunction_elem="";
    this.postloadfunction_data="";
    this.setpostloadfunction=function(func,elem,data)
    {
        this.postloadfunction=func;
        this.postloadfunction_elem=elem;
        this.postloadfunction_data=data;
    }
    
}

main_loader.ready();

