//FILE: js/elements/navbar/navbar_simple.js
/*******************************************************************************
*                                                                              *
*  This file has been generated by bmc.                                        *
*  Customizations should be done in bmc/elem/elements/<element_name>/elem.def. *
*                                                                              *
*******************************************************************************/



//class:
function navbar_simple(pdiv,wrap)
{
//constructor:
    this.wrap=wrap;
    
    this.box=document.createElement("div");
    this.box_inner=document.createElement("div");
    this.box.className="elem_navbar_box";
    this.box_inner.className="elem_navbar_box_inner";
    this.box.appendChild(this.box_inner);
    pdiv.appendChild(this.box);

    
    this.content="";
    this.cpage=currentpage;
    this.layout="standard";

//public:
    this.destroy=function()
    {
        
        pdiv.removeChild(this.box);
    }
    
    this.preset=function()
    {
        var o="\
                <div align='center'>\
                    loading...\
                </div>";
        this.box.innerHTML=o;

    }
    /*
    this.mbox=function()
    {
        return this.d4;
    }
    */
    
//private:
    
    this.onResize=function()
    {
        if(this.layout=="logo_layout")
        {
            if(screenx<580)
            {
                var o="";
                var lines=this.content.split("\n");
                for(var i=0;i<lines.length;i++)
                {
                    var a=lines[i].split("|");
                    if(a[2]==currentpage.substr(0,a[2].length))style="topnav2";else style="topnav";
                    o+="<a href=\""+a[1]+"\" class=\""+style+"\">"+a[0]+"</a>";
                    if(i==0)o+="<br>";
                    if(i>0 && i+1<lines.length)o+="&nbsp;|&nbsp;";
                }
                o+="</nobr>";
                this.box_inner.innerHTML=o;
            }
            else
            {
                var o="";
                var lines=this.content.split("\n");
                for(var i=0;i<lines.length;i++)
                {
                    var a=lines[i].split("|");
                    if(a[2]==currentpage.substr(0,a[2].length))style="topnav2";else style="topnav";
                    o+="<a href=\""+a[1]+"\" class=\""+style+"\">"+a[0]+"</a>";
                    if(i+1<lines.length)o+="&nbsp;|&nbsp;";
                }
                o+="</nobr>";
                this.box_inner.innerHTML=o;
            }
        }

    }
    
    this.setup=function(s)
    {
        elements_setup(s,this.wrap,"simple");
    }
}

main_loader.ready();

